[env:esp32_pc_control_deck]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI@2.5.31
    bblanchon/ArduinoJson@7.4.3

build_flags =
    -DUSER_SETUP_LOADED=1
    -DILI9341_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=4
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=27
    -DTFT_BACKLIGHT_ON=HIGH
    -DTOUCH_CS=33
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=16000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=1000000

[env:phos_inland_control_deck]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI@2.5.31
    bblanchon/ArduinoJson@7.4.3

build_flags =
    -DUSER_SETUP_LOADED=1
    -DPHOS_INLAND=1
    -DILI9341_DRIVER=1
    -DUSE_HSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=16000000

[env:phos_rain_candidate]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI@2.5.31
    https://github.com/0015/TP_Arduino_DigitalRain_Anim.git

build_flags =
    -DUSER_SETUP_LOADED=1
    -DPHOS_INLAND=1
    -DILI9341_DRIVER=1
    -DUSE_HSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=40000000
    -D RUN_CANDIDATE=1
build_src_filter = +<candidate.cpp> -<main.cpp> -<being.cpp>

[env:phos_being]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI@2.5.31
    bblanchon/ArduinoJson@7.4.3

build_flags =
    -DUSER_SETUP_LOADED=1
    -DPHOS_INLAND=1
    -DILI9341_DRIVER=1
    -DUSE_HSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=40000000
    -D RUN_BEING=1
build_src_filter = +<being.cpp> -<main.cpp> -<candidate.cpp>

[env:phos_eyes]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI@2.5.43

build_flags =
    -DUSER_SETUP_LOADED=1
    -DPHOS_INLAND=1
    -DILI9341_DRIVER=1
    -DUSE_HSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=40000000
build_src_filter = +<eyes.cpp> -<being.cpp> -<candidate.cpp>
